### ISSUE TITLE
Doesn't play all music in Modern UI

### ISSUE THREAD

**Issue by Ricotan-Linus** [suzukiplan/tohovgs4-android#18] opened 2022-01-30 07:18 UTC
Reproduction method
1.Install From Google Play Store
2.launch APP
3.Download New Music
4.Show advertisement
5.Push Play button

Environment
Redmi Note 9T (Softbank)
MIUI Global 12.5.7 Stable
Android 11 RP1A.200720.011

App Version
4.11

However Classic UI can play all music... but 
Can't background play... I want to be able that...

**Comment by suzukiplan** [comment] 2022-01-30 08:18
@Ricotan-naboon Thanks for reporting back!

I have investigated and found an issue https://github.com/suzukiplan/tohovgs4-android/commit/d891dd3e964f91cce390bd31884818a30c910301 with the logic when playing downloaded songs, so I assume that this is probably the cause of the issue you reported.

_I have not been able to reproduce the problem on my device, so I'm not sure if this will definitely fix it..._

I will update as soon as possible.

**Comment by Ricotan-naboon** [comment] 2022-01-30 08:35
Thanks.
After I report, I watch #17 And Try Install Ver 4.10 from Internet. Nevertheless happend same problem... So I downgrade Ver 2.06. It works Perfect.(I ignore Some Bug)

**Comment by Ricotan-naboon** [comment] 2022-01-30 08:41
P.S MIUIが入った泥と普通の泥って挙動違ったりします？それが仮に正しい場合上に上げた #17 が再現できないのも納得が付きます．

**Comment by suzukiplan** [comment] 2022-01-30 08:53
As for the cause of this problem (presumably), Android has a main thread (for UI processing)  and a sub-thread, and it is thought that the problem occurred because the main thread was executing processing that should have been executed in the sub-thread.

I noticed this when I checked with a feature in Android called [StrictMode](https://developer.android.com/reference/android/os/StrictMode).

In version 2.xx and Retro UI, the problem does not occur because all the procedures are execute in sub-threads, and I assume that the problem occurred in Modern UI.

他アプリ（MIUI）による影響という可能性もあるかもしれません。（それは気づかなかったので併せて調査してみます。情報ありがとうございます！）

**Comment by Ricotan-naboon** [comment] 2022-01-30 09:40
Ok. I wait release Ver 4.12...

**Comment by Ricotan-naboon** [comment] 2022-01-30 15:00
So I install Ver 4.12 from APK And I Confirmation fix that.
Thanks for Immediate fix and I'm sorry to support holiday...

**Comment by Ricotan-naboon** [comment] 2022-02-06 09:21
It happend after Ver 4.13 from google play store...

**Comment by suzukiplan** [comment] 2022-02-06 09:25
Okay... I'll reassess.

**Comment by suzukiplan** [comment] 2022-02-06 09:31
In ver4.13, some initialization processes are asynchronized to deal with the problem that loading Shared Preferences in the UI thread may result in ANR, which may be the effect, but not confirmed.
https://github.com/suzukiplan/tohovgs4-android/pull/22/files

**Comment by Ricotan-naboon** [comment] 2022-02-06 09:32
P.S 実機貸してもアリな気がしますがどうですか？

**Comment by Ricotan-naboon** [comment] 2022-02-06 09:34
Thanks. I try uninstall and install ver 4.12 from apk,It happen same problem...

**Comment by suzukiplan** [comment] 2022-02-06 09:46
If it's possible, I'll give you the debug build of the APK and you can install it and then do the following steps?

1. `adb install app-debug.apk`
2. `adb logcat > log.txt` 3.
3. Reproducing the problem
4. stop 2
4. send me the `log.txt` file.

**Comment by Ricotan-naboon** [comment] 2022-02-06 09:52
No Problem.
Please Send me as your like.
I'll do today.

**Comment by suzukiplan** [comment] 2022-02-06 09:53
Thank you!

app-debug.apk is here:
https://drive.google.com/file/d/1fYM5C10nWaH2WfUW8Xc0x4Jm2LkNOWuO/view?usp=sharing

**Comment by Ricotan-naboon** [comment] 2022-02-06 13:25
I dont know what happened, But It works You give apk use...
I think Cache happend that...(maybe)
Sorry to Useless debug...
![large-20200527230944-1](https://user-images.githubusercontent.com/51312671/152683086-fff1ae8e-9a5e-47ef-98e2-a0ecc30bc056.PNG)

**Comment by Ricotan-naboon** [comment] 2022-02-06 13:31
P.S 具体的にはキャッシュ一回削除してインストールしました．おそらく誤って4.12とか拾ってきた...?

**Comment by suzukiplan** [comment] 2022-02-06 13:53
I see.

There is a possibility that the problem is quite severe in terms of timing.

デバッグビルド版apkはリリースビルド版（GooglePlayで公開しているaab）と違ってminify（コード難読化）を実行していなかったり最適化されていないので、その影響で不具合が起きなかったりする...ということもあるかも。

**Comment by suzukiplan** [comment] 2022-02-06 14:42
Since there was another bug in the works, I submitted new version 4.14 for Google Play review without including the fix of this issue.

https://github.com/suzukiplan/tohovgs4-android/pull/24

**Comment by Ricotan-naboon** [comment] 2022-02-06 16:47
Ok. I delete cache and install Ver 4.14.
It works perfectly. 
And I try Reproduction again...

**Comment by Ricotan-naboon** [comment] 2022-02-06 16:48
ちょっと再現難しそうですね．そこまで絡むと...

**Comment by suzukiplan** [comment] 2022-02-07 07:56
This issue may be caused by the storage access, I think.

Downloaded songs are stored in the app's storage, and preset songs are stored in the app's assets (in the APK), which are technically both the same storage area, but accessing in different I/O APIs at the OS level.

Currently, ver4.14 is all songs are app's assets only, so I think it may happen again if new song is delivered and you have downloaded.

> _a new song will be delivered in this Saturday (if I can...)_

So, this issue will be keep open.

**Comment by Ricotan-naboon** [comment] 2022-02-07 11:09
ok. I will confirm this problem happen in Sat....

**Comment by suzukiplan** [comment] 2022-07-02 00:37
I'm closing this issue because it is highly likely that the following measures have been taken to completely fix the problem.
https://github.com/suzukiplan/tohovgs4-android/pull/36

**Closed by suzukiplan** 2022-07-02 00:37 UTC
Labels: bug
